project/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'project.views.index', name='home'),
    # url(r'^demo/', include('demo.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    #Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^services/', include('timebank.services.urls')),
    url(r'^reservations/', include('timebank.reservations.urls')),
    url(r'^accounts/', include('timebank.accounts.urls')),
    #url(r'^reservations/', include('timebank.reservations.urls')),
)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

timebank/accounts/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('timebank.accounts.views',
    (r'^$', 'my_account'),
)

timebank/reservations/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('timebank.reservations.views',
    #(r'^s/(?P<s_id>\w+)/$', 'service'),
    (r'^appointment/(?P<a_id>\w+)/$', 'appointment'),
    (r'^reserve/(?P<s_id>\w+)/$', 'reserve'),
    (r'^respond/(?P<r_id>\w+)/(?P<action>\w+)/$', 'respond'),
    (r'^appointments/$', 'appointments'),
    (r'^reservations/$', 'reservations'),
    
    
)

timebank/services/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('timebank.services.views',
    (r'^s/(?P<s_id>\w+)/$', 'service'),
    (r'^add/$', 'add'),
    (r'^my/$', 'my'),
    (r'^edit/(?P<s_id>\w+)/$', 'edit'),
    (r'^(?P<theme>\w+)/$', 'services'),
)

timebank/accounts/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from timebank.services.models import Service
from timebank.reservations.models import Appointment
#Penalty Period
PENALTY_HALF=4
PENALTY_FULL=1

class Account(models.Model):
    user = models.ForeignKey(User)
    balance=models.FloatField(default=0)     
    created_date  = models.DateTimeField(auto_now_add=True,editable=False,default=None,null=True,blank=True)
    changed  = models.DateTimeField(auto_now=True,editable=False,default=None,null=True,blank=True)
    #class Meta:
        #abstract= True
        #ordering = ['weight','id']
        #db_table = 'mockup_content_item'
        #app_label = "services"
    def get_notification(self,user):
        pass
    
"""
Records any action that might affect balance
"""
class Transaction(models.Model):
    user= models.ForeignKey(User)
    appointment=models.ForeignKey(Appointment)
    t_date  = models.DateTimeField(default=None,null=True,blank=True)
    amount = models.IntegerField(default=0,null=True,blank=True)
    payed_to = models.ForeignKey(User, related_name='payed_to')
    payed_by = models.ForeignKey(User, related_name='payed_by')
    created_date  = models.DateTimeField(auto_now_add=True,editable=False,default=None,null=True,blank=True)
    changed  = models.DateTimeField(auto_now=True,editable=False,default=None,null=True,blank=True)
    status=models.IntegerField(default=0,null=True,blank=True)
    closed = models.BooleanField()
    canceled= models.BooleanField()
    title=models.CharField(max_length=255,null=True,blank=True)
    comments=models.TextField(null=True,blank=True)
    action=models.IntegerField(null=True,blank=True)
    #class Meta:
        #abstract= True
        #ordering = ['weight','id']
        #db_table = 'mockup_content_item'
        #app_label = "services"
    def cancel(self):
        #reversing transaction 
        pass
    
class Transfer(models.Model):
    user=models.ForeignKey(User)
    transaction=models.ForeignKey(Transaction)
    balance=models.IntegerField(default=0,null=True,blank=True)
    amount=models.IntegerField(default=0,null=True,blank=True)
    created_date  = models.DateTimeField(auto_now_add=True,editable=False,default=None,null=True,blank=True)
    changed  = models.DateTimeField(auto_now=True,editable=False,default=None,null=True,blank=True)
    class Meta:
        ordering = ['-created_date']

"""
    @staticmethod
    def appointment_action(ap,action,user):
        try:
            tr=Transaction.objects.get(appointment=ap)
        except:
            tr=Transaction(appointment=ap)
        if action==10:
            tr.minutes=ap.length
            tr.payed_to=ap.service.owner
            tr.payed_by=ap.reciever
            pt_ac=Account.objects.get(user=tr.payed_to)
            pb_ac=Account.objects.get(user=tr.payed_by)
            pt_ac.balance+=tr.minutes
            pb_ac.balance-=tr.minutes
            tr.save()
            pt_ac.save()
            pb_ac.save()
            jr=Journal(transaction=tr,
                       created_by=user,
                       action=action,
                       payed_to=tr.payed_to,
                       payed_by=tr.payed_by
                       )
            jr.save()
            
            
        elif action==-4:#Cancel Service
            #TODO: if in no penalty period. 
            penalty_half=datetime.datetime.utcnow()-datetime.timedelta(days=PENALTY_HALF)
            penalty_full=datetime.datetime.utcnow()-datetime.timedelta(days=PENALTY_FULL)
            if ap.appointment_date>penalty_half:
                #clear the transaction- return all the money passed
                pass
            elif ap.appointment_date<penalty_full:
                #transaction is not change only mark it is a penalty
                #What do we do if one of the users did not show of
                pass
            else:
                #reverse earlier transaction, pass half of the penalty from the canceling user to the other user 
                pass
            if user==ap.reciever:
                pass
            elif user==ap.service.owner:
                pass
        elif action==-5:#Mutual Cancellation
            pt_ac=Account.objects.get(user=tr.payed_to)
            pb_ac=Account.objects.get(user=tr.payed_by)
            pt_ac.balance-=ap.length
            pb_ac.balance+=ap.length
            pt_ac.save()
            pb_ac.save()
            tr.payed_by=ap.service.owner
            tr.payed_to=ap.reciever
            tr.save()
            jr=Journal(transaction=tr,
                       created_by=user,
                       action=action,
                       payed_to=ap.reciever,
                       payed_by=ap.service.owner
                       )
            jr.save() 
            
            
            
        
                
        
        #TODO: Depending on the action set the transaction
        #Activate: pass time currency from provider to reciever
        #Cancel : depends on rules and who canceled    
        tr.save()
        
        #TODO: Change balance
        #TODO: This function should be a transaction from database point of view




class Journal(models.Model):
    transaction=models.ForeignKey(Transaction)
    action=models.IntegerField(default=0,null=True,blank=True)
    created_by = models.ForeignKey(User)
    minutes = models.IntegerField(default=0,null=True,blank=True)
    payed_by = models.ForeignKey(User,related_name='payed_by')
    payed_to = models.ForeignKey(User,related_name='payed_to')

""" 

timebank/conf/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.sites.models import Site

"""
TODO:Add setting for cancellation policy 
"""

class Conf(models.Model):
    max_minus  = models.FloatField()
    max_plus  = models.FloatField()
    allow_register  = models.BooleanField()
    review_service  = models.BooleanField()
    
    #class Meta:
        #abstract= True
        #ordering = ['weight','id']
        #db_table = 'mockup_content_item'
        #app_label = "services"


timebank/reservations/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from timebank.services.models import Service


class Appointment(models.Model):
    service = models.ForeignKey(Service)
    reciever = models.ForeignKey(User)    
    responder = models.ForeignKey(User,related_name='responder',null=True,blank=True)    
    appointment_date  = models.DateTimeField(default=None,null=True,blank=True)
    length  = models.IntegerField(default=60,null=True,blank=True)
    created= models.DateTimeField(auto_now_add=True,null=True,blank=True,editable=False)
    changed= models.DateTimeField(auto_now=True,null=True,blank=True,editable=False)
    comments=models.TextField(null=True,blank=True)
    status=models.IntegerField(default=1,null=True,blank=True,
                               choices=((1,_('Tentative')),
                                        (0,_('Rejected')),
                                        (10,_('Active')),
                                        (-4,_('Canceled')),
                                        ))
    class Meta:
        ordering =['-appointment_date']
    def activate(self):
        self.status=10
        """
        TODO: Add transaction
        """
        pass
    def cancel(self):
        self.status=-1
        """
        TODO: Add cancelation actions (transaction)
        """
    def reserve_action(self,action,user):
        from timebank.accounts import pass_currency 
        if user==self.reciever:
            self.responder=self.service.owner
        else:
            self.responder=self.reciever
        if action==10:
            self.status=10
            self.responder=None
            pass_currency(action,
                          self.length,
                          user,
                          self.reciever,
                          self.service.owner,
                          self,
                          '')
            self.save()
        elif action==1:
            self.status=0
            self.responder=None
            self.save()
                        


class Reservation(models.Model):
    appointment = models.ForeignKey(Appointment,null=True,blank=True)
    response_to = models.ForeignKey('self',null=True,blank=True)
    initiator = models.ForeignKey(User)    
    target = models.ForeignKey(User,related_name="target")    
    rdate  = models.DateTimeField(default=None,null=True,blank=True)
    minutes = models.IntegerField(default=60,null=True,blank=True)
    created_date  = models.DateTimeField(auto_now_add=True,editable=False,default=None,null=True,blank=True)
    location = models.CharField(max_length=255,null=True,blank=True)
    message=models.TextField(null=True,blank=True)
    viewed=models.BooleanField()
    response=models.BooleanField()
    
    status=models.IntegerField(default=0,null=True,blank=True,
                               choices=((0,_('Open')),
                                        (1,_('Closed')),
                                        ))
    action=models.IntegerField(default=0,null=True,blank=True,
                               choices=((0,_('Message')),
                                        (1,_('Reject')),
                                        (2,_('Change Date or Location')),
                                        (10,_('Accept')),
                                        (11,_('Cancel')),
                                        (12,_('Accept Cancel')),
                                        (13,_('Mutual Cancellation')),
                                        (14,_('Accept Mutual Cancellation')),
                                        ))
    class Meta:
        ordering =['-created_date']
        
    def respond(self):
        """
        Action that need to be taken on reservation respond
        """
        pass
    def set_appointment_old(self,user):
        self.appointment.reserve_action(self.action,user)
          
    def set_appointment(self,user,service=None):
        if self.response:
            self.appointment=self.response.appointment
            self.location=self.response.location
            self.rdate=self.response.rdate
            if self.action in [10,1,2]:
                self.response.status=1
        else:
            ap=Appointment(service=service,
                          reciever=user,
                          responder=service.owner,
                          appointment_date=self.rdate
                          )
            ap.save()
            self.appointment=ap
        self.save()
        self.appointment.reserve_action(self.action,user)
        #TODO: Generate notification
    def create_response(self,user):
        response=Reservation(appointment=self.appointment,
                     initiator=user,
                     target=self.initiator,
                     response_to=self)
        return response

timebank/reservations/forms.py
from django.forms import ModelForm

from timebank.reservations.models import Appointment,Reservation

class AppointmentForm(ModelForm):
    class Meta:
        model = Appointment
        fields = ('appointment_date',
                  'comments')
class ReservationForm(ModelForm):
    class Meta:
        model = Reservation
        fields = ('rdate',
                  'message',
                  'location'
                  )
        
class RespondForm(ModelForm):
    class Meta:
        model = Reservation
        fields = ('rdate',
                  'message',
                  'location',
                  'action'
                  )

timebank/services/forms.py
from django.forms import ModelForm

from timebank.services.models import Service

class ServiceForm(ModelForm):
    class Meta:
        model = Service
        fields = (
                  'title',
                  'theme',
                  'description',
                  'location',
                  'min_minutes',
                  'max_minutes' ,                 
                  'published')

timebank/accounts/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.utils.translation import ugettext as _
from django.utils import simplejson
from django.views.decorators.csrf import csrf_exempt
from timebank.accounts.models import Account,Transaction,Transfer

def my_account(request):
    account=Account.objects.get(user=request.user)
    transfers=Transfer.objects.filter(user=request.user)
    return render_to_response('accounts/my_account.html',
                              {'account':account,
                               'transfers':transfers},
            context_instance =  RequestContext(request)) 

timebank/conf/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.utils.translation import ugettext as _
from django.utils import simplejson
from django.views.decorators.csrf import csrf_exempt

from timebank.transactions.models import Transaction
from timebank.services.models import Service, Reservation

def search(request):
    return render_to_response('timebank/services/add_service.html',
                              {},
            context_instance =  RequestContext(request)) 

def add_service(request):
    return render_to_response('timebank/services/add_service.html',
                              {},
            context_instance =  RequestContext(request)) 
def edit_service(request):
    return render_to_response('timebank/services/add_service.html',
                              {},
            context_instance =  RequestContext(request)) 
def delete_service(request):
    return render_to_response('timebank/services/add_service.html',
                              {},
            context_instance =  RequestContext(request)) 

#list services
def services(request):
    return render_to_response('timebank/services/add_service.html',
                              {},
            context_instance =  RequestContext(request)) 
    
#admin
def admin_services(request):
    return render_to_response('timebank/services/add_service.html',
                              {},
            context_instance =  RequestContext(request)) 

timebank/templates/reservations/appointment.html
{% extends "base.html" %}
{% load url from future %}
{%load  i18n  %}
{%block body%}


<div id="appointment-{{ap.pk}}" data-role="page" class="page" data-dom-cache="false">
<div data-role="header" data-position="fixed" data-theme="b">
	<h1>{%trans 'Appointment'%}: {{ap.service.title}}</h1>
	<a href="/" data-icon="home" data-iconpos="notext" data-direction="reverse">Home</a>
	<a href="/search/" data-icon="search" data-iconpos="notext" data-rel="dialog" data-transition="fade">Search</a>
</div>
<div data-role="content">
<table>
<tr>
	<td>{%trans 'Service'%}</td>
	<td>{{ap.service.title}}</td>
</tr>
<tr>
	<td>{%trans 'Date'%}</td>
	<td>{{ap.appointment_date}}</td>
</tr>
<tr>
	<td>{%trans 'Status'%}</td>
	<td>{{ap.get_status_display}}</td>
</tr>
<tr>
	<td>{%trans 'Location'%}</td>
	<td>{{ap.location}}</td>
</tr>
</table>

<table>
<tr>
	<td>{%trans 'Date'%}</td>
	<td>{%trans 'Status'%}</td>
	<td>{%trans 'Location'%}</td>
	<td>{%trans 'Message'%}</td>
	<td>{%trans 'Action'%}</td>
</tr>
{%for r in ap.reservation_set.all%}
<tr>
	<td>{{r.rdate}}</td>
	<td>{{r.get_status_display}}</td>
	<td>{{r.location}}</td>
	<td>{{r.message}}</td>
	{%ifequal ap.status 1%}
	{%ifequal r.status 0%}
	{%ifequal r.target user%}
	<td><a href="/reservations/respond/{{r.pk}}/10/" data-icon="gear" data-rel="dialog" >{%trans 'Accept'%}</a></td> 
	<td><a href="/reservations/respond/{{r.pk}}/1/" data-icon="gear" data-rel="dialog">{%trans 'Reject'%}</a></td>
	<td><a href="/reservations/respond/{{r.pk}}/2/" data-icon="gear" data-rel="dialog">{%trans 'Reschedule'%}</a></td>
	{%else%}
	<td>{%trans 'Waiting for acceptance'%}</td>	
	{%endifequal%}
	{%endifequal%}
	{%endifequal%}
</tr>
{%endfor%}
</table>

</div><!-- /content -->			
{%include 'menu.html' %}
</div><!-- /page home-->

{%endblock body%}

timebank/templates/reservations/appointments.html
{% extends "base.html" %}
{% load url from future %}

{%load  i18n  %}
{%block body%}


<div id="appointments" data-role="page" class="page" data-dom-cache="false">

<div data-role="header" data-position="fixed" data-theme="b">
	<h1>{%trans 'My Reservations'%}</h1>
	<a href="/" data-icon="home" data-iconpos="notext" data-direction="reverse">Home</a>
	<a href="/search/" data-icon="search" data-iconpos="notext" data-rel="dialog" data-transition="fade">Search</a>
</div>
<div data-role="content">

<ul data-role="listview"  data-split-theme="d" data-filter="true">
<li data-role="list-divider">{%trans 'Appointments'%}</li>
{%for r in aps%}
<li><a href="/reservations/appointment/{{r.pk}}/" data-ajax='false' >
	<h3>{{r.service.title}}:{{r.appointment_date|date:"d/m/Y"}}</h3>
	<p>{%trans 'Status'%}:{{r.get_status_display}}</p>
	<p>{{r.service.owner}} -> {{r.reciever}}</p>
	</a>
</li>
{%endfor%}
</ul>

</div><!-- /content -->			
{%include 'menu.html' %}
</div><!-- /page home-->
{%endblock body%}

timebank/templates/reservations/reservations.html
{% extends "base.html" %}
{% load url from future %}

{%load  i18n  %}
{%block body%}


<div id="reservations" data-role="page" class="page" data-dom-cache="false">

<div data-role="header" data-position="fixed" data-theme="b">
	<h1>{%trans 'Reservations'%}</h1>
	<a href="/" data-icon="home" data-iconpos="notext" data-direction="reverse">Home</a>
	<a href="/search/" data-icon="search" data-iconpos="notext" data-rel="dialog" data-transition="fade">Search</a>
</div>
<div data-role="content">
<ul data-role="listview" >
	<li data-role="list-divider">{%trans 'Other members requesting my services'%}</li>
	{%for r in other_res %}
	<li><a href='/reservations/appointment/{{r.pk}}/' >{{r.service.title}} : {{r.appointment_date|date:"d/m/Y"}}</a></li>
	{%endfor%}
	<li data-role="list-divider">{%trans 'My reservations of other member services'%}</li>
	{%for r in my_res %}
	<li><a href='/reservations/appointment/{{r.pk}}/' >{{r.service.title}} : {{r.appointment_date|date:"d/m/Y"}}</a></li>
	{%endfor%}
</ul>


</div><!-- /content -->			
{%include 'menu.html' %}
</div><!-- /page home-->
{%endblock body%}

timebank/templates/reservations/reserve.html
{% extends "base.html" %}
{% load url from future %}

{%load  i18n  %}
{%block body%}


<div id="service-{{service.pk}}" data-role="page" class="page" data-dom-cache="true">

<div data-role="header" data-position="fixed" data-theme="b">
	<h1>{{service.title}}:{{service.owner}}</h1>
	<a href="/" data-icon="home" data-iconpos="notext" data-direction="reverse">Home</a>
	<a href="/search/" data-icon="search" data-iconpos="notext" data-rel="dialog" data-transition="fade">Search</a>
</div>
<div data-role="content">
<div>
	<div>{%trans 'Title'%}:{{service.title}}</div>
	<div>{%trans 'Description'%}:{{service.description}}</div>
	<div>{%trans 'Location'%}:{{service.location}}</div>
</div>
<form  method="post" >{%csrf_token%}
{% for field in form %}
<div data-role="fieldcontain">
	{{ field.label_tag }}
	{{ field }}
	{{ field.errors }}
</div>
{% endfor %}

<fieldset class="ui-grid-a">
	<div class="ui-block-a"><button value='cancel' type="button" onclick="go_home();" data-theme="d" data-mini="true">Cancel</button></div>
	<div class="ui-block-b"><button type="submit" data-theme="a" data-mini="true">Submit</button></div>
</fieldset>

<input name="mydate" id="mydate" type="date" data-role="datebox"
   data-options='{"mode": "calbox"}'>
   

</form>
</div><!-- /content -->			
{%include 'menu.html' %}
</div><!-- /page home-->


{%endblock body%}

timebank/templates/reservations/respond.html
{% extends "base.html" %}
{% load url from future %}

{%load  i18n  %}
{%block body%}


<div id="respond-{{respond.respond.pk}}" data-role="page" class="page" data-dom-cache="true">

<div data-role="header" data-position="fixed" data-theme="b">
	<h1>{{response.get_action_display}}</h1>
</div>
<div data-role="content">
<div>
	<div>{%trans 'Title'%}:{{response.appointment.service.title}}</div>
	<div>{%trans 'Date'%}:{{response.rdate}}</div>
	<div>{%trans 'Location'%}:{{response.location}}</div>
</div>
<form method="post" >{%csrf_token%}
<div style="display:none" >
	{{ form.action.label_tag }}
	{{ form.action }}
	{{ form.action.errors }}
	
</div>


<div data-role="fieldcontain">


	{%ifequal action '2' %}
	{{ form.rdate.label_tag }}
	{{ form.rdate }}
	{{ form.rdate.errors }}
	{{ form.location.label_tag }}
	{{ form.location }}
	{{ form.location.errors }}
	{%endifequal%}
	{{ form.message.label_tag }}
	{{ form.message }}
	{{ form.message.errors }}
</div>

<fieldset class="ui-grid-a">
	<div class="ui-block-a"><button value='cancel' type="button" onclick="go_home();" data-theme="d" data-mini="true">Cancel</button></div>
	<div class="ui-block-b"><button type="submit" data-theme="a" data-mini="true">Submit</button></div>
</fieldset>	
</form>
</div><!-- /content -->			
</div><!-- /page home-->


{%endblock body%}